# Generated by Django 2.0.3 on 2018-03-16 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emotion', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AddIndex(
            model_name='emotion',
            index=models.Index(fields=['email'], name='api_emotion_email_96b1b7_idx'),
        ),
        migrations.AddIndex(
            model_name='emotion',
            index=models.Index(fields=['emotion'], name='api_emotion_emotion_b4deb7_idx'),
        ),
    ]
